version: '3.3'
services:
  app:
    image: '12.16.3-stretch'
    build: .
    command: yarn start
    environment:
      - DATABASE_URL=postgres://tiket:tiket@db:5432/tiket
    ports:
    - 4000:4000
    links:
      - db
  db:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tiket
      - POSTGRES_DB=tiket-live
      - POSTGRES_PASSWORD=tiket
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data:
