version: '3.3'
services:
  redis:
    image: 'redis'
    ports:
      - 6379:6379
  db:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tiket
      - POSTGRES_DB=tiket-live
      - POSTGRES_PASSWORD=tiket
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data:
